Detection code for generic riscv and u74mc uarch.
archspec/archspec pull request #58
Opened 2021-10-02 04:43 UTC by ktpedre

Add function to detect processors of the riscv family.
Two riscv uarchs are supported, generic and u74mc.

This PR is dependent on https://github.com/archspec/archspec-json/pull/35 and will require the archspec-json submodule to be moved forward.

This commit passes all tox tests (which were run on riscv). It also properly detects the u74mc uarch when run on the SiFive Unleashed board.

2021-10-02 11:43 UTC, alalazo commented
Can you move the submodule forward, now that https://github.com/archspec/archspec-json/pull/35 has been merged?

2021-10-02 17:18 UTC, ktpedre commented
Thanks for merging https://github.com/archspec/archspec-json/pull/35. The archspec-json submodule is now moved forward in this PR. Note that I've only run the Python 3.8 tox tests, as I didn't have the other versions available. The tox tests output was...

```
  py38: commands succeeded
  pylint: commands succeeded
  flake8: commands succeeded
  black: commands succeeded
  congratulations :)
```

2021-10-03 11:46 UTC, alalazo requested changes
Changes LGTM, but there's another part that needs a one line modification. To run detection unit tests on the newly added /proc/cpuinfo sample for risc we need to add the filename to this list of parameters:

https://github.com/archspec/archspec/blob/5fcb4a28cceebf9c33ab8549cb99e273a0713e1e/tests/test_cpu.py#L44-L48

2021-10-03 16:40 UTC, ktpedre commented
In the process of adding linux-sifive-u74mc cpu test, I discovered the case where uarch!=u74mc was not being handled properly. That should be fixed by commit [6264978](https://github.com/archspec/archspec/pull/58/commits/626497853238d5c2441ff35971f71300907db4c7). For cases where u74mc is not matched, it falls back to a generic riscv64 target.

The linux-sifive-u74mc cpuinfo test is also added.

The tox tests still pass and running test_cpu.py also passes.

@alalazo, could you please take another look at both of these changes?

2021-10-04 09:04 UTC, merged